export const COUNTRY_NAMES: Record<string, string> = {
  US: "United States",
  GB: "United Kingdom",
  CA: "Canada",
  AU: "Australia",
  DE: "Germany",
  FR: "France",
  IN: "India",
  JP: "Japan",
  BR: "Brazil",
  NL: "Netherlands",
  SG: "Singapore",
  SE: "Sweden",
  IE: "Ireland",
  CH: "Switzerland",
  ES: "Spain",
  IT: "Italy",
  PL: "Poland",
  NZ: "New Zealand",
  MX: "Mexico",
  AR: "Argentina",
  ZA: "South Africa",
  AE: "UAE",
  IL: "Israel",
  KR: "South Korea",
  CN: "China",
  HK: "Hong Kong",
  PH: "Philippines",
  PK: "Pakistan",
  NG: "Nigeria",
  KE: "Kenya",
  EG: "Egypt",
  PT: "Portugal",
  BE: "Belgium",
  AT: "Austria",
  DK: "Denmark",
  NO: "Norway",
  FI: "Finland",
  CZ: "Czech Republic",
  RO: "Romania",
  CO: "Colombia",
  CL: "Chile",
  TW: "Taiwan",
  TH: "Thailand",
  MY: "Malaysia",
  ID: "Indonesia",
  VN: "Vietnam",
  RU: "Russia",
  UA: "Ukraine",
  TR: "Turkey",
  SA: "Saudi Arabia",
  QA: "Qatar",
  BD: "Bangladesh",
  LK: "Sri Lanka",
};

export const COUNTRY_FLAGS: Record<string, string> = {};
for (const code of Object.keys(COUNTRY_NAMES)) {
  COUNTRY_FLAGS[code] = String.fromCodePoint(
    ...code.split("").map((c) => 0x1f1e6 + c.charCodeAt(0) - 65)
  );
}

export const COLORS = {
  bg: "#0A0A0F",
  surface: "#12121A",
  surfaceHover: "#1A1A28",
  border: "#1E1E2E",
  accent: "#00E5A0",
  accentDim: "#00B37D",
  pin: "#FF4D4D",
  pinGlow: "#FF6B6B",
  text: "#F0F0F5",
  textMuted: "#8888A0",
  countryLow: "#0F1B3D",
  countryHigh: "#00E5A0",
};
